# Generated by Django 2.2.16 on 2021-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('u', 'user'), ('m', 'moderator'), ('a', 'admin')], max_length=1),
        ),
    ]
