# Generated by Django 2.2.16 on 2021-10-18 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211017_2347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
